module.exports = class Data1701178636101 {
    name = 'Data1701178636101'

    async up(db) {
        await db.query(`ALTER TABLE "market" DROP COLUMN "lifetime"`)
        await db.query(`ALTER TABLE "market" ADD "lifetime" integer NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "initial_margin"`)
        await db.query(`ALTER TABLE "market" ADD "initial_margin" integer NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "maintenance_margin"`)
        await db.query(`ALTER TABLE "market" ADD "maintenance_margin" integer NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "contract_unit"`)
        await db.query(`ALTER TABLE "market" ADD "contract_unit" integer NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "block_height"`)
        await db.query(`ALTER TABLE "market" ADD "block_height" integer NOT NULL`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "quantity"`)
        await db.query(`ALTER TABLE "order" ADD "quantity" integer NOT NULL`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "block_height"`)
        await db.query(`ALTER TABLE "order" ADD "block_height" integer NOT NULL`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "initial_quantity"`)
        await db.query(`ALTER TABLE "order" ADD "initial_quantity" integer NOT NULL`)
        await db.query(`ALTER TABLE "position" DROP COLUMN "quantity"`)
        await db.query(`ALTER TABLE "position" ADD "quantity" integer NOT NULL`)
        await db.query(`ALTER TABLE "position" DROP COLUMN "quantity_left"`)
        await db.query(`ALTER TABLE "position" ADD "quantity_left" integer NOT NULL`)
        await db.query(`ALTER TABLE "position" DROP COLUMN "block_height"`)
        await db.query(`ALTER TABLE "position" ADD "block_height" integer NOT NULL`)
        await db.query(`ALTER TABLE "aggregated_orders_by_price" DROP COLUMN "quantity"`)
        await db.query(`ALTER TABLE "aggregated_orders_by_price" ADD "quantity" integer NOT NULL`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "market" ADD "lifetime" numeric NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "lifetime"`)
        await db.query(`ALTER TABLE "market" ADD "initial_margin" numeric NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "initial_margin"`)
        await db.query(`ALTER TABLE "market" ADD "maintenance_margin" numeric NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "maintenance_margin"`)
        await db.query(`ALTER TABLE "market" ADD "contract_unit" numeric NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "contract_unit"`)
        await db.query(`ALTER TABLE "market" ADD "block_height" numeric NOT NULL`)
        await db.query(`ALTER TABLE "market" DROP COLUMN "block_height"`)
        await db.query(`ALTER TABLE "order" ADD "quantity" numeric NOT NULL`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "quantity"`)
        await db.query(`ALTER TABLE "order" ADD "block_height" numeric NOT NULL`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "block_height"`)
        await db.query(`ALTER TABLE "order" ADD "initial_quantity" numeric NOT NULL`)
        await db.query(`ALTER TABLE "order" DROP COLUMN "initial_quantity"`)
        await db.query(`ALTER TABLE "position" ADD "quantity" numeric NOT NULL`)
        await db.query(`ALTER TABLE "position" DROP COLUMN "quantity"`)
        await db.query(`ALTER TABLE "position" ADD "quantity_left" numeric NOT NULL`)
        await db.query(`ALTER TABLE "position" DROP COLUMN "quantity_left"`)
        await db.query(`ALTER TABLE "position" ADD "block_height" numeric NOT NULL`)
        await db.query(`ALTER TABLE "position" DROP COLUMN "block_height"`)
        await db.query(`ALTER TABLE "aggregated_orders_by_price" ADD "quantity" numeric NOT NULL`)
        await db.query(`ALTER TABLE "aggregated_orders_by_price" DROP COLUMN "quantity"`)
    }
}
